### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by farishkash** [SaraMohamedSamir/capstone_colmar#1]
You should only be writing a device media query for that specific once.

@media only screen and (max-width: 470px)

Also your media query should be after all your desktop css is done.

There is a few reasons for this, first when you write multiple media queries for the same device width css reads from top to bottom.  If your css is broken in one of the media queries of that device width it can break the rest of them following it.

@media only screen and (max-width: 470px)  <---first media query same width

@media only screen and (max-width: 470px)  **<--- if the css is broken in here, good chance it will break for the rest of the media queries below this.**

@media only screen and (max-width: 470px)  <--- third media query is broken because middle one is broken.

This makes it more difficult to find the error as you may have to search through multiple media queries of the same device width instead of one. You only really need to write this once and put all your css for each section underneath.

Second having only one at the bottom after all your desktop code creates a clear distinction of where the desktop css ends.

If you look at this screenshot below this is in the middle of your css file.  Am I in a media query or not?  Having media queries in the middle of the page creates the opportunity to edit the css for desktop when you meant mobile and vice versa.  If your media queries are at the bottom of the page, this great reduces the risk here.

![style_css_ _capstone_colmar-master](https://user-images.githubusercontent.com/5844161/32505820-f3f9a276-c397-11e7-8bcb-67bee439c538.jpg)

**Comment by SaraMohamedSamir** [comment]
thanks a lot for this important information, I fixed this issue and pushed the new code :)
now it is only one mobile query used for my style settings
